/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gisroad_jnitest_Jni */

#ifndef _Included_com_gisroad_jnitest_Jni
#define _Included_com_gisroad_jnitest_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gisroad_jnitest_Jni
 * Method:    getName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gisroad_jnitest_Jni_getName
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
